language: cpp
sudo: false
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
matrix:
  exclude:
    - os: osx
    - compiler: gcc

before_install:
  - cmake --version

script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=None -DBUILD_SHARED_LIBS:BOOL=ON -DDCMTK_WITH_OPENSSL:BOOL=ON -DDCMTK_WITH_PRIVATE_TAGS:BOOL=ON -DDCMTK_WITH_XML:BOOL=ON -DDCMTK_WITH_DOXYGEN:BOOL=OFF -DDCMTK_WITH_TIFF:BOOL=ON -DDCMTK_WITH_ZLIB:BOOL=ON -DDCMTK_WITH_WRAP:BOOL=ON -DDCMTK_WITH_ICONV:BOOL=ON -DUSE_COMPILER_HIDDEN_VISIBILITY:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_SKIP_RPATH:BOOL=OFF -DDCMTK_USE_CXX11_STL:BOOL=ON -DDCMTK_WITH_BUILTIN_DICTIONARY:BOOL=ON ..
  - make -j2
  - make test
